// Navigation
const SET_TAB = 'SET_TAB';
const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
const NAVIGATION_BACK = 'NAVIGATION_BACK';

export default {
  SET_TAB,
  NAVIGATION_FORWARD,
  NAVIGATION_BACK
};